"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: str = "0") -> bool:
    return str(os.getenv(name, default)).strip().lower() in (
        "1",
        "true",
        "yes",
        "y",
        "on",
    )


USE_POSTGRES = env_bool("USE_POSTGRES", "0")


def env(name: str, default: str = "") -> str:
    v = os.getenv(name)
    return default if v is None else str(v).strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h0trrw&$nr%mpbo6(ur=*i%3_xc^i0@$^_dv151!=trb$ey!qg"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "inventory",
    "django_filters",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}


ROOT_URLCONF = "erp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "erp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Local dev defaults to SQLite. Set USE_POSTGRES=1 (and PG_* vars) to switch to Postgres.


def _env_first(*keys: str, default: str = "") -> str:
    """Read settings with OS env taking priority over python-decouple (.env).

    This avoids a common gotcha where an existing .env file silently overrides
    PowerShell session variables (e.g., PG_PASSWORD), causing auth failures.
    """

    # 1) Prefer explicit process environment variables (PowerShell: $env:KEY="...").
    for k in keys:
        v = os.getenv(k)
        if v not in (None, ""):
            return v

    # 2) Fall back to python-decouple (e.g., .env file) if present.
    for k in keys:
        try:
            v = config(k, default=None)
        except Exception:
            v = None
        if v not in (None, ""):
            return str(v)

    return default


def _truthy(v: str) -> bool:
    return str(v).strip().lower() in ("1", "true", "yes", "y", "on")


USE_POSTGRES = _truthy(os.getenv("USE_POSTGRES", "0"))

if USE_POSTGRES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _env_first("PG_DB", "DB_NAME", default="erp"),
            "USER": _env_first("PG_USER", "DB_USER", default="erp"),
            "PASSWORD": _env_first("PG_PASSWORD", "DB_PASSWORD", default="erp"),
            "HOST": _env_first("PG_HOST", "DB_HOST", default="127.0.0.1"),
            "PORT": _env_first("PG_PORT", "DB_PORT", default="5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": _env_first("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": _env_first("DB_NAME", default=str(BASE_DIR / "db.sqlite3")),
            "USER": _env_first("DB_USER", default=""),
            "PASSWORD": _env_first("DB_PASSWORD", default=""),
            "HOST": _env_first("DB_HOST", default=""),
            "PORT": _env_first("DB_PORT", default=""),
        }
    }

# SQLite stability tweaks for tests/dev:
# - WAL: better concurrency for reads/writes
# - busy_timeout: wait a bit instead of failing with database table is locked
if DATABASES["default"]["ENGINE"].endswith("sqlite3"):
    # Point Django to our custom backend that runs PRAGMAs on every new connection.
    DATABASES["default"]["ENGINE"] = "erp.sqlite_backend"
    # Keep a reasonable sqlite driver timeout as well.
    DATABASES["default"].setdefault("OPTIONS", {})
    DATABASES["default"]["OPTIONS"].update(
        {
            "timeout": 5,  # seconds
        }
    )


SPECTACULAR_SETTINGS = {
    "TITLE": "ERP Inventory API",
    "DESCRIPTION": "Prototype ERP backend for products, orders, inventory and stock movements.",
    "VERSION": "1.0.0",
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
    "x-csrftoken",
]
