# Generated by Django 5.2.8 on 2026-01-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
